use russiawc;
db.dropDatabase();

db.games.insertMany([
  {
    round: 'Group Stages',
    location: 'Volgograd',
    home_team: 'Tunisia',
    away_team: 'England',
    home_goals: 1,
    away_goals: 2,
    home_tactics: '4-3-3',
    away_tactics: '3-5-2',
    home_yellow: 0,
    home_red: 0,
    away_yellow: 1,
    away_red: 0,
    home_possession: 41,
    away_possession: 59,
    home_attempts: 6,
    away_attempts: 18,
    home_fouls: 14,
    away_fouls: 8,
    extra_time: false,
    penalties: false,
    hints: ['Home team goal scorer plays his club football in Saudi Arabia', 'Penalty conceded by an ex Sheffield Utd player', 'Extra time goal', 'Home team governing body CAF', 'Away team governing body UEFA']
  },
  {
    round: 'Group Stages',
    location: 'Sochi',
    home_team: 'Portugal',
    away_team: 'Spain',
    home_goals: 3,
    away_goals: 3,
    home_tactics: '4-2-3-1',
    away_tactics: '4-2-3-1',
    home_yellow: 1,
    home_red: 0,
    away_yellow: 1,
    away_red: 0,
    home_possession: 39,
    away_possession: 61,
    home_attempts: 8,
    away_attempts: 12,
    home_fouls: 12,
    away_fouls: 10,
    extra_time: false,
    penalties: false,
    hints: ['There was a hat-trick in the match', 'A player born in Lagarto, Brazil scored twice', 'A defender scored with a volley', 'An ex Manchester United player was given MOTM', 'Both teams qualified from the group']
  },
  {
    round: 'Group Stages',
    location: 'Kazan',
    home_team: 'France',
    away_team: 'Australia',
    home_goals: 2,
    away_goals: 1,
    home_tactics: '4-3-3',
    away_tactics: '4-2-3-1',
    home_yellow: 1,
    home_red: 0,
    away_yellow: 3,
    away_red: 0,
    home_possession: 51,
    away_possession: 49,
    home_attempts: 12,
    away_attempts: 4,
    home_fouls: 16,
    away_fouls: 19,
    extra_time: false,
    penalties: false,
    hints: ['Controversial penalty given to the favourites', 'A deflected own goal won the game', 'Away team governing body OFC', 'A penalty was scored by an Aston Villa player', 'The winner won the group, the looser finished bottom']
  },
  {
    round: 'Round of 16',
    location: 'Rostov-On-Don',
    home_team: 'Belgium',
    away_team: 'Japan',
    home_goals: 3,
    away_goals: 2,
    home_tactics: '3-4-3',
    away_tactics: '4-2-3-1',
    home_yellow: 0,
    home_red: 0,
    away_yellow: 1,
    away_red: 0,
    home_possession: 56,
    away_possession: 44,
    home_attempts: 24,
    away_attempts: 11,
    home_fouls: 13,
    away_fouls: 9,
    extra_time: false,
    penalties: false,
    hints: ['The winners came from two goals down to win', 'The winning goal came in the 94th minute', 'The opening goal was scored by a Hannover 96 player', 'Home team governing body UEFA', 'Away team governing body AFC']
  },
  {
    round: 'Round of 16',
    location: 'Moscow',
    home_team: 'Colombia',
    away_team: 'England',
    home_goals: 1,
    away_goals: 1,
    home_tactics: '4-3-2-1',
    away_tactics: '3-5-2',
    home_yellow: 6,
    home_red: 0,
    away_yellow: 2,
    away_red: 0,
    home_possession: 48,
    away_possession: 52,
    home_attempts: 14,
    away_attempts: 16,
    home_fouls: 23,
    away_fouls: 13,
    extra_time: true,
    penalties: true,
    hints: ['There were 8 penalties in total in the game', '93rd minute header took the game to extra time', 'Home team goal scorer plays for Barcelona', 'The golden boot winner scored in this match', 'Home team governing body CONMEBOL']
  },
  {
    round: 'Round of 16',
    location: 'Moscow',
    home_team: 'Spain',
    away_team: 'Russia',
    home_goals: 1,
    away_goals: 1,
    home_tactics: '4-2-3-1',
    away_tactics: '5-3-2',
    home_yellow: 1,
    home_red: 0,
    away_yellow: 2,
    away_red: 0,
    home_possession: 74,
    away_possession: 26,
    home_attempts: 25,
    away_attempts: 6,
    home_fouls: 5,
    away_fouls: 19,
    extra_time: true,
    penalties: true,
    hints: ['Home team dominated with 1107 passes', 'Both goals came in the first half', 'A Celta de Vigo player missed the decisive penalty', 'Home manager sacked pre tournament', 'Both teams governed by UEFA']
  },
  {
    round: 'Quarter Finals',
    location: 'Kazan',
    home_team: 'Brazil',
    away_team: 'Belgium',
    home_goals: 1,
    away_goals: 2,
    home_tactics: '4-2-3-1',
    away_tactics: '3-4-3',
    home_yellow: 2,
    home_red: 0,
    away_yellow: 2,
    away_red: 0,
    home_possession: 57,
    away_possession: 43,
    home_attempts: 26,
    away_attempts: 8,
    home_fouls: 14,
    away_fouls: 15,
    extra_time: false,
    penalties: false,
    hints: ['Both teams ranked in the top 5 pre World Cup', 'The EPL playmaker of the season scored', 'An injury time penalty appeal was denied for the home team', 'Away team governing body UEFA', 'Home team governing body CONMEBOL']
  },
  {
    round: 'Round of 16',
    location: 'Kazan',
    home_team: 'France',
    away_team: 'Argentina',
    home_goals: 4,
    away_goals: 3,
    home_tactics: '4-2-3-1',
    away_tactics: '4-3-3',
    home_yellow: 3,
    home_red: 0,
    away_yellow: 5,
    away_red: 0,
    home_possession: 41,
    away_possession: 59,
    home_attempts: 9,
    away_attempts: 9,
    home_fouls: 21,
    away_fouls: 15,
    extra_time: false,
    penalties: false,
    hints: ['2 goals from the Young Player of the tournament', '5 second half goals', 'Away team reached 2014 final', 'Home team governing body UEFA', 'The winners went on to win the world cup']
  },
  {
    round: 'Group Stage',
    location: 'Moscow',
    home_team: 'Germany',
    away_team: 'Mexico',
    home_goals: 0,
    away_goals: 1,
    home_tactics: '4-2-3-1',
    away_tactics: '4-2-3-1',
    home_yellow: 2,
    home_red: 0,
    away_yellow: 2,
    away_red: 0,
    home_possession: 60,
    away_possession: 40,
    home_attempts: 25,
    away_attempts: 12,
    home_fouls: 10,
    away_fouls: 15,
    extra_time: false,
    penalties: false,
    hints: ['Home team reached 2014 final', 'Both teams played in 2017 Confederations Cup', 'Goal scorer plays for PSV', 'Home team governing body UEFA', 'Away team governing body CONCACAF']
  },
  {
    round: 'Quarter Finals',
    location: 'Moscow',
    home_team: 'Russia',
    away_team: 'Croatia',
    home_goals: 2,
    away_goals: 2,
    home_tactics: '4-2-3-1',
    away_tactics: '4-2-3-1',
    home_yellow: 1,
    home_red: 0,
    away_yellow: 4,
    away_red: 0,
    home_possession: 36,
    away_possession: 64,
    home_attempts: 13,
    away_attempts: 17,
    home_fouls: 25,
    away_fouls: 18,
    extra_time: true,
    penalties: true,
    hints: ['4th goal scored by a Brazillian', 'Away team reached the final', 'Both away team goals were headers', 'Both teams governing body UEFA', 'Home teams first QF since 1970']
  }
])
